### ISSUE TITLE
[Idea] adding the skillshottype

### ISSUE THREAD

**Issue by marpme** [LeagueSharp/LeagueSharp.Data#13]
Hey there,

would you mind to add the **skillshottype** to the spelldatabase ? :+1: 

greets Kyon

**Comment by marpme** [comment]
If you want, I can add this for you :)

**Comment by ChewyMoon** [comment]
Hi! Fortunately enough the spell database has a `SpellType` property which should contain what you're looking for.

**Comment by ghost** [comment]
I faced the same issue yesterday. Simply did that now:
https://gist.github.com/legacy3/ae045230393345dd31ab1a6f1106ee84#file-spellfactory-cs-L61

**Comment by marpme** [comment]
yeah that's cool 👍 

btw liked your exception in the method above 😄
