### ISSUE TITLE
ItemDatabaseEntry lacks Item id and "From" properties 

### ISSUE THREAD

**Issue by Esk0r** [LeagueSharp/LeagueSharp.Data#33]
Fix plz ![FeelsSadMan](https://cdn.joduska.me/forum/public/style_emoticons/default/feelssadman.png)

**Comment by ghost** [comment]
@ChewyMoon :clock1:

**Comment by Esk0r** [comment]
![biblethump](https://cdn.joduska.me/forum/public/style_emoticons/default/1612039156_biblethump.png)

**Comment by ghost** [comment]
:waiting:

**Comment by ChewyMoon** [comment]
Added!
